# Generated by Django 5.0.2 on 2024-02-16 21:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(4)])),
                ('dob', models.DateField()),
                ('guardian_name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=500)),
                ('date_of_enrollment', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=100)),
                ('previous_school', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gender')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade')),
                ('guardian_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.guardianrelation')),
            ],
        ),
    ]
