# Generated by Django 5.0.2 on 2024-02-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Address',
            new_name='address',
        ),
    ]
