# Generated by Django 5.0.2 on 2024-02-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_student_address_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_relation',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='child',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='GuardianRelation',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
