# Generated by Django 5.0.2 on 2024-02-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_employmentstatus_role_subject_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Subject',
            new_name='subject',
        ),
    ]
