# Generated by Django 5.0.2 on 2024-02-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_staff_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
