# Generated by Django 5.0.2 on 2024-02-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_staff_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guardianrelation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
