# Generated by Django 5.0.2 on 2024-02-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_gender_status_grade_status_guardianrelation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentstatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
