# Generated by Django 5.0.2 on 2024-02-18 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_employmentstatus_status_role_status_subject_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAndTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('period_one_timing', models.TimeField()),
                ('period_two_timing', models.TimeField()),
                ('period_three_timing', models.TimeField()),
                ('period_four_timing', models.TimeField()),
                ('period_five_timing', models.TimeField()),
                ('period_six_timing', models.TimeField()),
                ('period_seven_timing', models.TimeField()),
                ('class_incharge', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.staff')),
                ('period_five_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_five_teacher', to='school.staff')),
                ('period_four_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_four_teacher', to='school.staff')),
                ('period_one_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_one_teacher', to='school.staff')),
                ('period_seven_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_seven_teacher', to='school.staff')),
                ('period_six_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_six_teacher', to='school.staff')),
                ('period_three_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_three_teacher', to='school.staff')),
                ('period_two_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_two_teacher', to='school.staff')),
                ('periods_five_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_five_subject', to='school.subject')),
                ('periods_four_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_four_subject', to='school.subject')),
                ('periods_one_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_one_subject', to='school.subject')),
                ('periods_seven_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_seven_subject', to='school.subject')),
                ('periods_six_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_six_subject', to='school.subject')),
                ('periods_three_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_three_subject', to='school.subject')),
                ('periods_two_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_two_subject', to='school.subject')),
                ('subjects', models.ManyToManyField(to='school.subject')),
            ],
        ),
    ]
