# Generated by Django 5.0.2 on 2024-02-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_classandtiming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classandtiming',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade'),
        ),
    ]
