# Generated by Django 5.0.2 on 2024-02-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_classandtiming_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classandtiming',
            old_name='periods_five_subject',
            new_name='period_five_subject',
        ),
        migrations.RenameField(
            model_name='classandtiming',
            old_name='periods_four_subject',
            new_name='period_four_subject',
        ),
        migrations.RenameField(
            model_name='classandtiming',
            old_name='periods_one_subject',
            new_name='period_one_subject',
        ),
        migrations.RenameField(
            model_name='classandtiming',
            old_name='periods_seven_subject',
            new_name='period_seven_subject',
        ),
        migrations.RenameField(
            model_name='classandtiming',
            old_name='periods_six_subject',
            new_name='period_six_subject',
        ),
        migrations.RenameField(
            model_name='classandtiming',
            old_name='periods_three_subject',
            new_name='period_three_subject',
        ),
        migrations.RenameField(
            model_name='classandtiming',
            old_name='periods_two_subject',
            new_name='period_two_subject',
        ),
    ]
