# Generated by Django 5.0.2 on 2024-02-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_rename_periods_five_subject_classandtiming_period_five_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classandtiming',
            old_name='period_five_timing',
            new_name='period_seven_from',
        ),
        migrations.RenameField(
            model_name='classandtiming',
            old_name='period_four_timing',
            new_name='period_six_to',
        ),
        migrations.RemoveField(
            model_name='classandtiming',
            name='period_one_timing',
        ),
        migrations.RemoveField(
            model_name='classandtiming',
            name='period_seven_timing',
        ),
        migrations.RemoveField(
            model_name='classandtiming',
            name='period_six_timing',
        ),
        migrations.RemoveField(
            model_name='classandtiming',
            name='period_three_timing',
        ),
        migrations.RemoveField(
            model_name='classandtiming',
            name='period_two_timing',
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_five_from',
            field=models.TimeField(default='02:12:00'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_five_to',
            field=models.TimeField(default='02:12:00'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_four_from',
            field=models.TimeField(default='02:12:00'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_four_to',
            field=models.TimeField(default='02:12:00'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_one_from',
            field=models.TimeField(default='02:12:00'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_one_to',
            field=models.TimeField(default='02:12:00'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_seven_to',
            field=models.TimeField(default='02:12:00'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_six_from',
            field=models.TimeField(default='02:12:00'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_three_from',
            field=models.TimeField(default='02:12:00'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_three_to',
            field=models.TimeField(default='02:12:00'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_two_from',
            field=models.TimeField(default='02:12:00'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_two_to',
            field=models.TimeField(default='02:12:00'),
        ),
    ]
