# Generated by Django 5.0.2 on 2024-02-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_rename_period_five_timing_classandtiming_period_seven_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classandtiming',
            name='period_five_from',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_five_to',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_four_from',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_four_to',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_one_from',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_one_to',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_seven_from',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_seven_to',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_six_from',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_six_to',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_three_from',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_three_to',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_two_from',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='period_two_to',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
