# Generated by Django 5.0.2 on 2024-02-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_alter_classandtiming_period_five_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentstatus',
            old_name='employment_status',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='name',
        ),
    ]
