# Generated by Django 5.0.2 on 2024-02-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_rename_employment_status_employmentstatus_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classandtiming',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
