# Generated by Django 5.0.2 on 2024-02-18 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_classandtiming_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classandtiming',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='employmentstatus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='status',
        ),
        migrations.RemoveField(
            model_name='guardianrelation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='role',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='status',
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='class_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.grade'),
        ),
    ]
