# Generated by Django 5.0.2 on 2024-02-19 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_remove_classandtiming_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classandtiming',
            name='class_incharge',
        ),
        migrations.AlterField(
            model_name='classandtiming',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.grade'),
        ),
    ]
