# Generated by Django 5.0.2 on 2024-02-19 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_remove_classandtiming_class_incharge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_incharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classandtiming')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.staff')),
            ],
        ),
    ]
