# Generated by Django 5.0.2 on 2024-02-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_class_incharge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='class_incharge',
            new_name='ClassIncharge',
        ),
        migrations.RenameField(
            model_name='classincharge',
            old_name='class_name',
            new_name='class_obj',
        ),
    ]
