# Generated by Django 5.0.2 on 2024-02-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_rename_class_incharge_classincharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classincharge',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='classincharge',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_relation',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='subject',
        ),
        migrations.DeleteModel(
            name='ClassAndTiming',
        ),
        migrations.DeleteModel(
            name='ClassIncharge',
        ),
        migrations.DeleteModel(
            name='EmploymentStatus',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='GuardianRelation',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
