# Generated by Django 5.0.2 on 2024-02-25 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0029_remove_classincharge_class_obj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClassAndTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_one_from', models.TimeField(default='00:00:00')),
                ('period_one_to', models.TimeField(default='00:00:00')),
                ('period_two_from', models.TimeField(default='00:00:00')),
                ('period_two_to', models.TimeField(default='00:00:00')),
                ('period_three_from', models.TimeField(default='00:00:00')),
                ('period_three_to', models.TimeField(default='00:00:00')),
                ('period_four_from', models.TimeField(default='00:00:00')),
                ('period_four_to', models.TimeField(default='00:00:00')),
                ('period_five_from', models.TimeField(default='00:00:00')),
                ('period_five_to', models.TimeField(default='00:00:00')),
                ('period_six_from', models.TimeField(default='00:00:00')),
                ('period_six_to', models.TimeField(default='00:00:00')),
                ('period_seven_from', models.TimeField(default='00:00:00')),
                ('period_seven_to', models.TimeField(default='00:00:00')),
                ('status', models.BooleanField(default=True)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('salary', models.CharField(max_length=20)),
                ('contract_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.BooleanField(default=True)),
                ('employment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.employmentstatus')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gender')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.role')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ClassIncharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classandtiming')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.staff')),
            ],
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_five_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_five_teacher', to='school.staff'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_four_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_four_teacher', to='school.staff'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_one_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_one_teacher', to='school.staff'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_seven_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_seven_teacher', to='school.staff'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_six_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_six_teacher', to='school.staff'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_three_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_three_teacher', to='school.staff'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_two_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_two_teacher', to='school.staff'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('guardian_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('date_of_enrollment', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=100)),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gender')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade')),
                ('guardian_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.guardianrelation')),
            ],
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_five_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_five_subject', to='school.subject'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_four_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_four_subject', to='school.subject'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_one_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_one_subject', to='school.subject'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_seven_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_seven_subject', to='school.subject'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_six_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_six_subject', to='school.subject'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_three_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_three_subject', to='school.subject'),
        ),
        migrations.AddField(
            model_name='classandtiming',
            name='period_two_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_two_subject', to='school.subject'),
        ),
    ]
