# Generated from local migration policy check on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_erp_student_staff_profile_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancesession',
            old_name='school_atte_attenda_8eaa5f_idx',
            new_name='school_atte_attenda_dafb17_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancesession',
            old_name='school_atte_grade_i_226646_idx',
            new_name='school_atte_grade_i_d5409d_idx',
        ),
        migrations.RenameIndex(
            model_name='feeinvoice',
            old_name='school_feei_due_dat_d18f46_idx',
            new_name='school_feei_due_dat_9548f1_idx',
        ),
        migrations.RenameIndex(
            model_name='feeinvoice',
            old_name='school_feei_status_825db3_idx',
            new_name='school_feei_status_ced0a4_idx',
        ),
        migrations.RenameIndex(
            model_name='feeinvoice',
            old_name='school_feei_student_7596ad_idx',
            new_name='school_feei_student_c237c7_idx',
        ),
        migrations.RenameIndex(
            model_name='librarybook',
            old_name='school_libr_title_70f98d_idx',
            new_name='school_libr_title_c64781_idx',
        ),
        migrations.RenameIndex(
            model_name='librarybook',
            old_name='school_libr_isbn_31967e_idx',
            new_name='school_libr_isbn_e94175_idx',
        ),
        migrations.RenameIndex(
            model_name='librarybook',
            old_name='school_libr_accessi_9e9df1_idx',
            new_name='school_libr_accessi_f63b28_idx',
        ),
        migrations.RenameIndex(
            model_name='librarybook',
            old_name='school_libr_categor_51f62b_idx',
            new_name='school_libr_categor_20e184_idx',
        ),
        migrations.RenameIndex(
            model_name='librarybook',
            old_name='school_libr_is_acti_2209c3_idx',
            new_name='school_libr_is_acti_75747b_idx',
        ),
        migrations.RenameIndex(
            model_name='libraryissue',
            old_name='school_libr_issue_d_c3b8e9_idx',
            new_name='school_libr_issue_d_bc9db4_idx',
        ),
        migrations.RenameIndex(
            model_name='libraryissue',
            old_name='school_libr_due_dat_a314c7_idx',
            new_name='school_libr_due_dat_60627d_idx',
        ),
        migrations.RenameIndex(
            model_name='libraryissue',
            old_name='school_libr_status_7cef13_idx',
            new_name='school_libr_status_6b845b_idx',
        ),
        migrations.RenameIndex(
            model_name='libraryissue',
            old_name='school_libr_student_2070e6_idx',
            new_name='school_libr_student_aa4675_idx',
        ),
        migrations.RenameIndex(
            model_name='loginactivity',
            old_name='school_logi_created_5c920b_idx',
            new_name='school_logi_created_6d734e_idx',
        ),
        migrations.RenameIndex(
            model_name='loginactivity',
            old_name='school_logi_ip_addr_54731c_idx',
            new_name='school_logi_ip_addr_94a95a_idx',
        ),
        migrations.RenameIndex(
            model_name='loginactivity',
            old_name='school_logi_is_succ_276d20_idx',
            new_name='school_logi_is_succ_00b1f9_idx',
        ),
        migrations.RenameIndex(
            model_name='loginactivity',
            old_name='school_logi_usernam_fa16f4_idx',
            new_name='school_logi_usernam_d4d36f_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            old_name='school_mess_sender__7a336d_idx',
            new_name='school_mess_sender__0a959f_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            old_name='school_mess_recipie_1d47cd_idx',
            new_name='school_mess_recipie_fbbe7b_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            old_name='school_mess_priorit_c5f092_idx',
            new_name='school_mess_priorit_b1899c_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            old_name='school_mess_is_read_ec00e3_idx',
            new_name='school_mess_is_read_359c37_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            old_name='school_mess_last_ac_bdc38f_idx',
            new_name='school_mess_last_ac_cc8d94_idx',
        ),
        migrations.RenameIndex(
            model_name='notice',
            old_name='school_noti_publish_9ba5e2_idx',
            new_name='school_noti_publish_dbfc55_idx',
        ),
        migrations.RenameIndex(
            model_name='notice',
            old_name='school_noti_audienc_20c79a_idx',
            new_name='school_noti_audienc_41a65e_idx',
        ),
        migrations.RenameIndex(
            model_name='notice',
            old_name='school_noti_priorit_84cd7c_idx',
            new_name='school_noti_priorit_31a44f_idx',
        ),
        migrations.RenameIndex(
            model_name='notice',
            old_name='school_noti_is_publ_1f75b9_idx',
            new_name='school_noti_is_publ_ca20de_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolcalendarevent',
            old_name='school_scho_event_d_9ebfd7_idx',
            new_name='school_scho_event_d_db142d_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolcalendarevent',
            old_name='school_scho_event_t_2f0bc3_idx',
            new_name='school_scho_event_t_414a3d_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolcalendarevent',
            old_name='school_scho_audienc_119ef4_idx',
            new_name='school_scho_audienc_2d3152_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolcalendarevent',
            old_name='school_scho_is_acti_4e5fd2_idx',
            new_name='school_scho_is_acti_e112cc_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolexpense',
            old_name='school_scho_payment_562553_idx',
            new_name='school_scho_payment_8a7c2f_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolexpense',
            old_name='school_scho_categor_ba76ac_idx',
            new_name='school_scho_categor_3a8507_idx',
        ),
        migrations.RenameIndex(
            model_name='studentattendance',
            old_name='school_stud_status_3f8049_idx',
            new_name='school_stud_status_3ecf89_idx',
        ),
        migrations.RenameIndex(
            model_name='studentattendance',
            old_name='school_stud_student_3a9ed6_idx',
            new_name='school_stud_student_350650_idx',
        ),
        migrations.RenameIndex(
            model_name='threadmessage',
            old_name='school_thre_thread__693de7_idx',
            new_name='school_thre_thread__79cd9c_idx',
        ),
        migrations.RenameIndex(
            model_name='threadmessage',
            old_name='school_thre_author__5873d2_idx',
            new_name='school_thre_author__3d9c9b_idx',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='onlineadmissionapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='onlineadmissionapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentcomplaint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parentcomplaint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['grade', 'start_date'], name='school_exam_grade_i_b5fc80_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_published'], name='school_exam_is_publ_6cfb50_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['student'], name='school_stud_student_b4f353_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['exam_subject'], name='school_stud_exam_su_0ce13c_idx'),
        ),
    ]
