from django.shortcuts import render

from .access_control import admin_required


STUDENT_FIELDS = [
    {"label": "Student Name", "value": "{{ student.name }}"},
    {"label": "Urdu Name", "value": "{{ student.student_name_urdu }}"},
    {"label": "Father Name", "value": "{{ student.father_name }}"},
    {"label": "Class", "value": "{{ student.grade }}"},
    {"label": "Roll No", "value": "{{ student.roll_no }}"},
    {"label": "Admission No", "value": "{{ student.admission_no }}"},
    {"label": "GR No", "value": "{{ student.gr_no }}"},
    {"label": "Guardian Phone", "value": "{{ student.phone }}"},
]

STAFF_FIELDS = [
    {"label": "Staff Name", "value": "{{ member.name }}"},
    {"label": "Staff Code", "value": "{{ member.staff_code }}"},
    {"label": "Role", "value": "{{ member.role }}"},
    {"label": "Subject", "value": "{{ member.subject }}"},
    {"label": "Department", "value": "{{ member.department }}"},
    {"label": "CNIC", "value": "{{ member.cnic }}"},
    {"label": "Phone", "value": "{{ member.phone }}"},
    {"label": "WhatsApp", "value": "{{ member.whatsapp_no }}"},
]


TEMPLATE_PREVIEWS = [
    {
        "title": "Student Bio Data",
        "category": "Students",
        "icon": "fa-file-lines",
        "badge": "Profile",
        "description": "Student profile, guardian information, class details and photo area.",
        "sample": "The HTML template pulls these columns from the selected Student object.",
        "fields": STUDENT_FIELDS + [
            {"label": "Address", "value": "{{ student.address }}"},
            {"label": "Photo Path", "value": "{{ student.photo_path }}"},
        ],
    },
    {
        "title": "Staff Bio Data",
        "category": "Staff",
        "icon": "fa-user-tie",
        "badge": "Profile",
        "description": "Staff profile sheet with role, subject, CNIC, contact and department.",
        "sample": "The HTML template pulls these columns from the selected Staff object.",
        "fields": STAFF_FIELDS + [
            {"label": "Qualification", "value": "{{ member.qualification }}"},
            {"label": "Photo Path", "value": "{{ member.photo_path }}"},
        ],
    },
    {
        "title": "Student ID Card",
        "category": "Cards",
        "icon": "fa-id-badge",
        "badge": "Card",
        "description": "Compact printable ID card design for students.",
        "sample": "ID card values are filled dynamically from the Student row.",
        "fields": [
            {"label": "Student", "value": "{{ student.name }}"},
            {"label": "Class", "value": "{{ student.grade }}"},
            {"label": "Roll No", "value": "{{ student.roll_no }}"},
            {"label": "Admission No", "value": "{{ student.admission_no }}"},
            {"label": "Guardian", "value": "{{ student.guardian_name }}"},
            {"label": "Phone", "value": "{{ student.phone }}"},
            {"label": "Blood Group", "value": "{{ student.blood_group }}"},
            {"label": "Photo", "value": "{{ student.photo_path }}"},
        ],
    },
    {
        "title": "Staff ID Card",
        "category": "Cards",
        "icon": "fa-address-card",
        "badge": "Card",
        "description": "Printable ID card for teaching and staff members.",
        "sample": "Staff card values are filled dynamically from the Staff row.",
        "fields": [
            {"label": "Staff", "value": "{{ member.name }}"},
            {"label": "Staff Code", "value": "{{ member.staff_code }}"},
            {"label": "Role", "value": "{{ member.role }}"},
            {"label": "Subject", "value": "{{ member.subject }}"},
            {"label": "Phone", "value": "{{ member.phone }}"},
            {"label": "CNIC", "value": "{{ member.cnic }}"},
            {"label": "Department", "value": "{{ member.department }}"},
            {"label": "Photo", "value": "{{ member.photo_path }}"},
        ],
    },
    {
        "title": "Welcome Card",
        "category": "Students",
        "icon": "fa-gift",
        "badge": "Card",
        "description": "New admission welcome card with sent/pending workflow.",
        "sample": "Welcome card uses live Student data and sent status columns.",
        "fields": [
            {"label": "Student", "value": "{{ student.name }}"},
            {"label": "Class", "value": "{{ student.grade }}"},
            {"label": "Admission", "value": "{{ student.admission_no }}"},
            {"label": "Roll No", "value": "{{ student.roll_no }}"},
            {"label": "Guardian", "value": "{{ student.guardian_name }}"},
            {"label": "Enrollment", "value": "{{ student.date_of_enrollment }}"},
            {"label": "Sent", "value": "{{ student.welcome_card_sent }}"},
            {"label": "Sent At", "value": "{{ student.welcome_card_sent_at }}"},
        ],
    },
    {
        "title": "Certificates",
        "category": "Documents",
        "icon": "fa-award",
        "badge": "Print",
        "description": "Portrait Character, Hope, Provisional, Leaving and Appreciation certificates.",
        "sample": "Certificate heading/body changes by certificate type and student values come from the Student row.",
        "fields": [
            {"label": "Certificate Title", "value": "{{ certificate.title }}"},
            {"label": "Heading", "value": "{{ certificate.heading }}"},
            {"label": "Student", "value": "{{ student.name }}"},
            {"label": "Father", "value": "{{ student.father_name }}"},
            {"label": "Class", "value": "{{ student.grade }}"},
            {"label": "Roll No", "value": "{{ student.roll_no }}"},
            {"label": "Admission", "value": "{{ student.admission_no }}"},
            {"label": "Issue Date", "value": "{{ print_date }}"},
        ],
    },
    {
        "title": "Advisory Letters",
        "category": "Documents",
        "icon": "fa-triangle-exclamation",
        "badge": "Letter",
        "description": "Parent communication letters for conduct, attendance, office reminder and performance.",
        "sample": "Letter subject/body changes by advisory type and student values come from the Student row.",
        "fields": [
            {"label": "Letter Title", "value": "{{ letter.title }}"},
            {"label": "Subject", "value": "{{ letter.subject }}"},
            {"label": "Student", "value": "{{ student.name }}"},
            {"label": "Guardian", "value": "{{ student.guardian_name }}"},
            {"label": "Class", "value": "{{ student.grade }}"},
            {"label": "Roll No", "value": "{{ student.roll_no }}"},
            {"label": "Admission", "value": "{{ student.admission_no }}"},
            {"label": "Date", "value": "{{ print_date }}"},
        ],
    },
    {
        "title": "Fee Voucher",
        "category": "Finance",
        "icon": "fa-receipt",
        "badge": "Voucher",
        "description": "School and parent copy of fee voucher with fee heads and balance.",
        "sample": "Voucher values are filled dynamically from FeeInvoice and Student relations.",
        "fields": [
            {"label": "Invoice ID", "value": "{{ invoice.id }}"},
            {"label": "Student", "value": "{{ invoice.student.name }}"},
            {"label": "Class", "value": "{{ invoice.student.grade }}"},
            {"label": "Billing", "value": "{{ invoice.billing_month }}"},
            {"label": "Due Date", "value": "{{ invoice.due_date }}"},
            {"label": "Net Total", "value": "{{ invoice.net_total }}"},
            {"label": "Paid", "value": "{{ invoice.amount_paid }}"},
            {"label": "Balance", "value": "{{ invoice.balance_due }}"},
        ],
    },
    {
        "title": "Dues Statement",
        "category": "Finance",
        "icon": "fa-money-bill-wave",
        "badge": "Dues",
        "description": "Student dues statement with copyable WhatsApp message.",
        "sample": "Dues statement uses Student, invoice list and calculated total_due context.",
        "fields": [
            {"label": "Student", "value": "{{ student.name }}"},
            {"label": "Class", "value": "{{ student.grade }}"},
            {"label": "Phone", "value": "{{ student.phone }}"},
            {"label": "WhatsApp", "value": "{{ student.whatsapp_no }}"},
            {"label": "Invoices", "value": "{% for invoice in invoices %}"},
            {"label": "Balance Row", "value": "{{ invoice.balance_due }}"},
            {"label": "Total Due", "value": "{{ total_due }}"},
            {"label": "Message", "value": "{{ whatsapp_text }}"},
        ],
    },
    {
        "title": "Exam Date Sheet",
        "category": "Exams",
        "icon": "fa-calendar-days",
        "badge": "Schedule",
        "description": "Class-wise printable examination date sheet.",
        "sample": "Date sheet table uses exam context and generated rows from exam subjects.",
        "fields": [
            {"label": "Exam", "value": "{{ exam.name }}"},
            {"label": "Class", "value": "{{ exam.grade }}"},
            {"label": "Start Date", "value": "{{ exam.start_date }}"},
            {"label": "Paper Date", "value": "{{ row.date }}"},
            {"label": "Day", "value": "{{ row.day }}"},
            {"label": "Subject", "value": "{{ row.subject.name }}"},
            {"label": "Time", "value": "{{ row.time }}"},
            {"label": "Marks", "value": "{{ row.total_marks }}"},
        ],
    },
    {
        "title": "Result Card",
        "category": "Exams",
        "icon": "fa-square-poll-vertical",
        "badge": "Result",
        "description": "Student and bulk result card printing for exam marks.",
        "sample": "Result card values come from exam, student and calculated result rows.",
        "fields": [
            {"label": "Exam", "value": "{{ exam.name }}"},
            {"label": "Student", "value": "{{ student.name }}"},
            {"label": "Subject", "value": "{{ subject.subject.name }}"},
            {"label": "Marks", "value": "{{ subject.marks }}"},
            {"label": "Total", "value": "{{ result.total }}"},
            {"label": "Obtained", "value": "{{ result.obtained }}"},
            {"label": "Percentage", "value": "{{ result.percentage }}"},
            {"label": "Status", "value": "{{ result.status }}"},
        ],
    },
    {
        "title": "Staff Lecture Attendance Report",
        "category": "Attendance",
        "icon": "fa-clipboard-user",
        "badge": "Report",
        "description": "Staff lecture attendance report with summary and print option.",
        "sample": "Report rows use session, summary and staff attendance records.",
        "fields": [
            {"label": "Session", "value": "{{ session.title }}"},
            {"label": "Date", "value": "{{ session.session_date }}"},
            {"label": "Taken By", "value": "{{ session.taken_by }}"},
            {"label": "Staff", "value": "{{ record.staff.name }}"},
            {"label": "Role", "value": "{{ record.staff.role }}"},
            {"label": "Status", "value": "{{ record.get_status_display }}"},
            {"label": "Lecture", "value": "{{ record.lecture_title }}"},
            {"label": "Remarks", "value": "{{ record.remarks }}"},
        ],
    },
    {
        "title": "Learning Resource",
        "category": "Study",
        "icon": "fa-book-open-reader",
        "badge": "Resource",
        "description": "Class and subject wise learning material detail page.",
        "sample": "Resource detail uses the StudyMaterial model fields directly.",
        "fields": [
            {"label": "Title", "value": "{{ material.title }}"},
            {"label": "Class", "value": "{{ material.grade }}"},
            {"label": "Subject", "value": "{{ material.subject }}"},
            {"label": "Description", "value": "{{ material.description }}"},
            {"label": "Content", "value": "{{ material.content }}"},
            {"label": "External URL", "value": "{{ material.external_url }}"},
            {"label": "Published", "value": "{{ material.is_published }}"},
            {"label": "Share Text", "value": "{{ share_text }}"},
        ],
    },
    {
        "title": "Vendor Account",
        "category": "Ledger",
        "icon": "fa-store",
        "badge": "Ledger",
        "description": "Vendor ledger with debit/credit entries and running balance.",
        "sample": "Vendor ledger uses Vendor and VendorLedgerEntry model fields.",
        "fields": [
            {"label": "Vendor", "value": "{{ vendor.name }}"},
            {"label": "Phone", "value": "{{ vendor.phone }}"},
            {"label": "Entry Date", "value": "{{ entry.entry_date }}"},
            {"label": "Description", "value": "{{ entry.description }}"},
            {"label": "Debit", "value": "{{ entry.debit }}"},
            {"label": "Credit", "value": "{{ entry.credit }}"},
            {"label": "Method", "value": "{{ entry.payment_method }}"},
            {"label": "Balance", "value": "{{ balance }}"},
        ],
    },
    {
        "title": "Cashbook",
        "category": "Ledger",
        "icon": "fa-cash-register",
        "badge": "Register",
        "description": "Cash and bank transaction register.",
        "sample": "Cashbook uses CashBankAccount and CashBankTransaction model fields.",
        "fields": [
            {"label": "Account", "value": "{{ tx.account.name }}"},
            {"label": "Type", "value": "{{ tx.get_transaction_type_display }}"},
            {"label": "Date", "value": "{{ tx.transaction_date }}"},
            {"label": "Title", "value": "{{ tx.title }}"},
            {"label": "Amount", "value": "{{ tx.amount }}"},
            {"label": "Note", "value": "{{ tx.note }}"},
            {"label": "Created By", "value": "{{ tx.created_by }}"},
            {"label": "Opening", "value": "{{ account.opening_balance }}"},
        ],
    },
]


@admin_required
def template_preview_center(request):
    return render(request, "template_preview_center.html", {"templates": TEMPLATE_PREVIEWS})
